#!/bin/bash
#
# Example for the University of Cambridge Computer Laboratory
#
# Scan all NFS exports of file server "elmer" on a managed
# Linux server for files that need renumbering towards
# implementing the number-allocation scheme described at
#
#   https://wiki.cam.ac.uk/cl-sys-admin/UID/GID_allocation
#
# We scan snapshots, where available, to avoid updating atime
# fields of scanned directories.
#
# A typical scan takes a bit over 6 hours.
#
nice ./ugid-scan -U nonascii-filenames \
        -u 1100-3600,0-1,3611-9499 \
        -g 1100-3600,0-1,3611-10000,19-20 $* \
        -n '/.snapshot/sv_daily.0' '' \
        /Nfs/Mounts/elmer-vol{1,3,4,5,6,8}/.snapshot/sv_daily.0 \
        /Nfs/Mounts/elmer-vol{7,9}
